- name: Deploy to Tomcat
  hosts: web
  gather_facts: yes

  tasks:
    - name: Ensure webapps directory is group‑writable
      ansible.builtin.file:
        path: /opt/tomcat/webapps
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0775'
        recurse: yes

    - name: Copy WAR file to Tomcat
      ansible.builtin.copy:
        src: "/var/lib/jenkins/workspace/MavenAnsibleWebApp1CICD/target/MavenAnsibleWebApp1.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebApp1.war"
        remote_src: yes
        mode: '0644'
      # note: no owner/group here, so no chown attempt :contentReference[oaicite:0]{index=0}

    - name: Restart Tomcat
      ansible.builtin.systemd:
        name: tomcat
        state: restarted
        daemon_reload: yes

