- name: Deploy to Tomcat
  hosts: web
  gather_facts: yes    # you can omit this too if you don't need facts
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/lib/jenkins/workspace/MavenAnsibleWebApp1CICD/target/MavenAnsibleWebApp.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebApp.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
