- name: Deploy to Tomcat
  hosts: web
  gather_facts: yes
  vars_files:
    - vault.yml
  vars:
    ansible_become_password: "root"

  tasks:
    - name: Ensure /opt/tomcat/webapps is writable
      ansible.builtin.file:
        path: /opt/tomcat/webapps
        state: directory
        mode: '0777'
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Copy WAR file to Tomcat
      ansible.builtin.copy:
        src: "/var/lib/jenkins/workspace/MavenAnsibleWebApp1CICD/target/MavenAnsibleWebApp1.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebApp1.war"
        remote_src: yes
        owner: tomcat
        group: tomcat
        mode: '0777'

    - name: Restart Tomcat
      ansible.builtin.systemd:
        name: tomcat
        state: restarted
        daemon_reload: yes
