- name: Deploy to Tomcat
  hosts: web
  gather_facts: yes    # no become, so facts are gathered as root without sudo

  tasks:
    - name: Copy WAR file to Tomcat
      ansible.builtin.copy:
        src: "/var/lib/jenkins/workspace/MavenAnsibleWebApp1CICD/target/MavenAnsibleWebApp.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebApp.war"
        remote_src: yes
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Restart Tomcat
      ansible.builtin.systemd:
        name: tomcat
        state: restarted
        daemon_reload: yes

